---
name: ORCA CI
on:
  push:
    # Prevent duplicate jobs on Dependabot PRs that interfere with automerge.
    branches-ignore:
      - 'dependabot/**'
  pull_request: ~
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORCA_SUT_NAME: acquia/memcache-settings
      ORCA_SUT_BRANCH: main
      ORCA_VERSION: ^3
      ORCA_JOB: ${{ matrix.orca-job }}
      ORCA_COVERALLS_ENABLE: ${{ matrix.coveralls-enable }}
      COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        orca-job:
          - STATIC_CODE_ANALYSIS
          - INTEGRATED_TEST_ON_OLDEST_SUPPORTED
          - INTEGRATED_TEST_ON_PREVIOUS_MINOR
          - INTEGRATED_TEST_ON_CURRENT
          - ISOLATED_TEST_ON_CURRENT_DEV
          - INTEGRATED_TEST_ON_CURRENT_DEV
          - STRICT_DEPRECATED_CODE_SCAN
          - ISOLATED_TEST_ON_NEXT_MINOR
          - INTEGRATED_TEST_ON_NEXT_MINOR
          - DEPRECATED_CODE_SCAN_W_CONTRIB
          - INTEGRATED_TEST_ON_NEXT_MINOR_DEV
          - ISOLATED_TEST_ON_NEXT_MINOR_DEV
          - LOOSE_DEPRECATED_CODE_SCAN
        php-version: [ "8.1" ]
        orca-coveralls-enable: [ "FALSE" ]
        orca-enable-nightwatch: [ "FALSE" ]
        include:
          - orca-job: STATIC_CODE_ANALYSIS
            php-version: "8.1"
            orca-coveralls-enable: "FALSE"
            orca-enable-nightwatch: "FALSE"

          - orca-job: INTEGRATED_TEST_ON_OLDEST_SUPPORTED
            php-version: "7.4"
            orca-coveralls-enable: "FALSE"
            orca-enable-nightwatch: "FALSE"

          - orca-job: INTEGRATED_TEST_ON_OLDEST_SUPPORTED
            php-version: "8.0"
            orca-coveralls-enable: "FALSE"
            orca-enable-nightwatch: "FALSE"

          - orca-job: INTEGRATED_TEST_ON_LATEST_LTS
            php-version: "7.4"
            orca-coveralls-enable: "FALSE"
            orca-enable-nightwatch: "FALSE"

          - orca-job: ISOLATED_TEST_ON_CURRENT
            php-version: "8.1"
            orca-coveralls-enable: "FALSE"
            orca-enable-nightwatch: "TRUE"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Before install
        run: |
          composer create-project --no-dev acquia/orca ../orca "$ORCA_VERSION"
          ../orca/bin/ci/before_install.sh

      - name: Install
        run: ../orca/bin/ci/install.sh

      - name: Before script
        run: ../orca/bin/ci/before_script.sh

      - name: Script
        run: ../orca/bin/ci/script.sh

      - name: After script
        run: ../orca/bin/ci/after_script.sh

      - name: After success
        if: ${{ success() }}
        run: ../orca/bin/ci/after_success.sh

      - name: After failure
        if: ${{ failure() }}
        run: ../orca/bin/ci/after_failure.sh

  all-successful:
    if: always()
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
      - name: All checks successful
        run: echo "🎉"
